export const GET_POST_DATA = 'GET_POST_DATA';
export const GET_POST_DATA_PENDING = 'GET_POST_DATA_PENDING';
export const GET_POST_DATA_FAIL = 'GET_POST_DATA_FAIL';
export const GET_POST_DATA_SUCCESS = 'GET_POST_DATA_SUCCESS';

export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const VERIFY_TOKEN_PENDING = 'VERIFY_TOKEN_PENDING';
export const VERIFY_TOKEN_FAIL = 'VERIFY_TOKEN_FAIL';
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';

export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_PENDING = 'LIKE_POST_PENDING';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';

export const UNLIKE_POST = 'UNLIKE_POST';
export const UNLIKE_POST_PENDING = 'UNLIKE_POST_PENDING';
export const UNLIKE_POST_FAIL = 'UNLIKE_POST_FAIL';
export const UNLIKE_POST_SUCCESS = 'UNLIKE_POST_SUCCESS';

export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_PENDING = 'GET_COMMENTS_PENDING';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';

export const SEND_COMMENTS = 'SEND_COMMENTS';
export const SEND_COMMENTS_PENDING = 'SEND_COMMENTS_PENDING';
export const SEND_COMMENTS_FAIL = 'SEND_COMMENTS_FAIL';
export const SEND_COMMENTS_SUCCESS = 'SEND_COMMENTS_SUCCESS';

