export const GET_ABOUT_DATA = 'GET_ABOUT_DATA';
export const GET_ABOUT_DATA_PENDING = 'GET_ABOUT_DATA_PENDING';
export const GET_ABOUT_DATA_FAIL = 'GET_ABOUT_DATA_FAIL';
export const GET_ABOUT_DATA_SUCCESS = 'GET_ABOUT_DATA_SUCCESS';

export const GET_SPONSOR_DATA = 'GET_SPONSOR_DATA';
export const GET_SPONSOR_DATA_PENDING = 'GET_SPONSOR_DATA_PENDING';
export const GET_SPONSOR_DATA_FAIL = 'GET_SPONSOR_DATA_FAIL';
export const GET_SPONSOR_DATA_SUCCESS = 'GET_SPONSOR_DATA_SUCCESS';