//Types SIGN UP -  Registro
export const CALL_REGISTER = 'CALL_REGISTER';
export const CALL_REGISTER_PENDING = 'CALL_REGISTER_PENDING';
export const CALL_REGISTER_SUCCESS = 'CALL_REGISTER_SUCCESS';
export const CALL_REGISTER_FAIL = 'CALL_REGISTER_FAIL';