export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_TOKEN_PENDING = 'SAVE_TOKEN_PENDING';
export const SAVE_TOKEN_SUCCESS = 'SAVE_TOKEN_SUCCESS';
export const SAVE_TOKEN_FAIL = 'SAVE_TOKEN_FAIL';

