export const RECOVERY_PASSWORD = 'RECOVERY_PASSWORD';
export const RECOVERY_PASSWORD_PENDING = 'RECOVERY_PASSWORD_PENDING';
export const RECOVERY_PASSWORD_FAIL = 'RECOVERY_PASSWORD_FAIL';
export const RECOVERY_PASSWORD_SUCCESS = 'RECOVERY_PASSWORD_SUCCESS';