export const GET_DATA_USER = "GET_DATA_USER";
export const GET_DATA_USER_PENDING = "GET_DATA_USER_PENDING";
export const GET_DATA_USER_SUCCESS = "GET_DATA_USER_SUCCESS";
export const GET_DATA_USER_FAIL = "GET_DATA_USER_FAIL";

export const UPDATE_DATA_USER = "UPDATE_DATA_USER";
export const UPDATE_DATA_USER_PENDING = "UPDATE_DATA_USER_PENDING";
export const UPDATE_DATA_USER_SUCCESS = "UPDATE_DATA_USER_SUCCESS";
export const UPDATE_DATA_USER_FAIL = "UPDATE_DATA_USER_FAIL";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_PENDING = "LOGOUT_USER_PENDING";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";