export const GET_ANIMALS = 'GET_ANIMALS';
export const GET_ANIMALS_PENDING = 'GET_ANIMALS_PENDING';
export const GET_ANIMALS_FAIL = 'GET_ANIMALS_FAIL';
export const GET_ANIMALS_SUCCESS = 'GET_ANIMALS_SUCCESS';

export const GET_ANIMALS_GALLERY = 'GET_ANIMALS_GALLERY';
export const GET_ANIMALS_GALLERY_PENDING = 'GET_ANIMALS_GALLERY_PENDING';
export const GET_ANIMALS_GALLERY_FAIL = 'GET_ANIMALS_GALLERY_FAIL';
export const GET_ANIMALS_GALLERY_SUCCESS = 'GET_ANIMALS_GALLERY_SUCCESS';

export const ADOPT = 'ADOPT';
export const ADOPT_PENDING = 'ADOPT_PENDING';
export const ADOPT_FAIL = 'ADOPT_FAIL';
export const ADOPT_SUCCESS = 'ADOPT_SUCCESS';

